### ISSUE TITLE
Use of collections of content

### ISSUE THREAD

**Issue by levelos** [hsus/changing-lives#2]
E.g., within a campaign, currently

```
goals:
  goal1: "Expand our enormously successful Pets for Life mentorship program, helping 200,000 animals in five years."
  goal2: "Reduce by 200,000 the number of puppies produced by puppy mills by strengthening animal welfare standards, restricting retail sales of puppy mill dogs and persuading pet stores to promote adoption of homeless animals."
  goal3: "Extend our international street dog initiative to vaccinate and sterilize more than a million street dogs and convince more governments to stop culls."
```

Should be,

```
goals:
  - "Expand our enormously successful Pets for Life mentorship program, helping 200,000 animals in five years."
  - "Reduce by 200,000 the number of puppies produced by puppy mills by strengthening animal welfare standards, restricting retail sales of puppy mill dogs and persuading pet stores to promote adoption of homeless animals."
  - "Extend our international street dog initiative to vaccinate and sterilize more than a million street dogs and convince more governments to stop culls."
```
